title: s12f
description: all about compute science
theme: just-the-docs
url: https://s12f.github.io

defaults:
  - scope:
      path: "posts"
      type: "pages"
    values:
      layout: "default"

color_scheme: blue_light

math: katex

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# aux_links:
#   "GitHub":
#     - "https://github.com/s12f/s12f.github.io"
