title: s12f
description: all about compute science
theme: just-the-docs
url: https://s12f.github.io

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

color_scheme: blue_light

# aux_links:
#   "GitHub":
#     - "https://github.com/s12f/s12f.github.io"
